env:
  global:
    - secure: EwPJfCD7eB9wAboA62TIjJhVw9xCqM0qeuDj7m0duy+9RzOviYWfhJz0gHx7LQcOtFpqzGDT8FozM4uxm+/SswTqybNYdaZSyVEjfrN/qyQ1furDjsZA0jBfX0q9E+VT+Xfj9RfwikNFpa1+Ckd57pp9IcjK3ovFtALFfJAizDXVMFvM/6+MyDXSdEAQ9JmSL2/Gda2mnZKjJ+SeyAI6k8fjAQHD+pxNus87jMj+2RuCnCFjGXO2kpwKM7cbhg16XczT+VbH+eOWfAfpNF0pg7p1lqqXZ4b84UW8EZ0JSmn/sT8/o7poq/IR1Ms+FlDG2/mos6mbHpiYw6MthJt7Yi3vthzi6jWBIAPIq7BpwI8oNe4R/D+0vo3jJcgoFoHXRO1KLOMi4gG8rwSLJxIAPysznRpOqjcS6VMMysdDhxYeUdHkS+CGh2Ue8YO9w3VOj6ePnr0lNCJjILnFk9leeIsfors/DK+oHXW0GKW5xY3FxYcDxNnC3dpuqVH3tDu/esft8C+6/xMgblW/9WesyE/zCxlqNjpcahJAsMuw9FtQcKbGTxkwkW6eYfAtl9bM7m7DatdkLW7ujmd6ureXuaOvRPkzhIsGBoF/1WbVup95Y6H5lLk+g7FIvQCxhLFBw9MKQAxip9I3uGTqE2/WJWzSPn87QOJ4by20PH+J7+g=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Spam404
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
