env:
  global:
    - secure: ZNwxJep9KC99dSMQc/gQGVrS2qa+mGFPOVsA7yO2YhmsGHaW50++CSfPDDURqt53WPSY0vonjeBvvuK4HnIODDzkSdnMd3I2aIiZdlhmvclE2WtbmdtFXXfNMrkjPUKSbQROb0tq8+lG5ekhfNwPeT5aCILMVqBAxo1bGamLGc5TbDoO5mAP78Febhp0n/MwnGdgWGZJjBVg1dp84NXY1ORAvIosK9Jq70kgH5GrfjWr3glO+tVelOU1+8ILY94cO/6r0XX/HnJlMyYbdQS3HScC1gyszaUNw28kjGWrr00fmrwtTB2OM39XEFZjc/WGsfcFb4bvqJ26mtBqYhbNKV2ldn/Ve7FhklN6cuJ3lCZaeTnOghDl+6z23IhMoncvJ8b8/d3+sOEEiDb9SstUblyOh3JoLxqwe8aYkSb8Z/9QfDNmTpksV/GLUY6Xvko93CIWOaDey3MwIZ5H+PTppaf5+1ovyUhuF/n9/h8LY9KCNUlGecnHG82LRII3DVKCZvME/0kkM5P3Hu9RuZWtz5tlXmmoGN14/3O4LNLIFmpkcumWEYA5vMyjmhIHEuuvLIHMTe23ep412L/KiwsdBv2bO6LKrkZt1QSoSsU0o/w0Owax89qzHIAGuJQjnQzc+abbo4W0acVlCbCMm1t9ozrvyB+Rw6nu6wehy91iw/0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Spam404
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
