env:
  global:
    - secure: Z93eGmAGcHlpKt0/v33bayFagRCQdqvLyuMvyNWFyZQabri0Ogm4ORiRXys0Y8RQ/IsDNU5XWyQFQrjKU26rc9lqe15xnZEx8jr5NMQTDwHXxD/Vl+2QROQNpkpeRskVi7TkR9cZMNhfQUyVg7wuh55IVwdQrtmVgx1OR7IhQO6KB9EA/Xdoc3ADSpY362/KDnI7hzQoHW6+V610Fo2ZM5rryg3gc0JAWtkY/sASt7+dd2CiZ9FO/T+Q0DoljKuqDT5jzzYSaos/xAEwD33gSQLU1B3HPGuqgNGQ4SBft3ljD+mUumMW0a44DRY7NAvYXRJ0nXtXoSwLKOEeB9AEAIfxMwAc3fpmUIl7DCnTMTrcNgftfiIpcmsKOYxa9QqhdTPOgp+f9MDcIQceMCPfHxMi9QiQ1kfFbZOytR0GOUGziXB3GSns3tJ9MrcSKMzGsaw5z68TPgyr6QSveKfIdXumBTDwIfzlzWOx322VleU7+NNRfg5ZoGMxX+9fWIOd5Lw6+G7/WvScFOKdzT0je2xkLPvZYo8csrWGC05CuL3V4BiWecgOTo6eAOcs+0+GdEVXS/QRElWa3JMpY1OaNv8Xw9W/TV9n9Tr9FGBXwuXL64uL4QQ52aNynmRPwGqwgtLD4/rMphXMy4YbK+995ZZhedIMUkfLObg8UWeSptU=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Spam404
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
