env:
  global:
    - secure: g6JtMlglfRAxXRSs81sjCM/qInF0xYyafPpv91bovV4sLnuLmswB696+ainIHVL/0BsZUqN2FdcRHdXui6UurErULQ0f7v6i30YSpfPLr4+0sP+9Q7WxOVhJy5AhQ4KrBe/HtWMDkWqaIJJQFWHVWJXynT+PypW/F3A4/e75tjRr0uNiEkIY8dgXi2IB2aelr3wXxbZXVu915toeBQ8i+0lWQ4kdABYK1FLGd1mBztG/ONfZs3AVJXCkR4znjWukdzM6tpzG2lGYocmP24n5uPi7Gu9Bb8C5DzF4QxdxS0I2zZ2vGQxpssRJIYaWx9FcLWTIEvb0bgE/7vOTT9Bv0yZTT5zB0NbIOUZDIAkP4jD6xUkL63wbXLGzb8volptU+pc2Tz7dYSafRJhuqp8GiPuAbfNrKek57E/wBk+2iO6zjpqv8kH9UsjmAsWdfiBnEKjyDyB/1ACfr5HX3nq909xPmDA2LVxVXiFuvvJDarpNXAvKwIlBhTuR7uJIQk/iNGvolDzlrMqgmeKzY1hpIY5WGY0JwzLy/HQiHYy61hQxsYdiU6pkUOthHDRTC+A4Ek409ZdyFJ6djV+8oXY8+FDvpb6Ruf2br+Vxo+p22rhNC14NMajYxAtNUEeeArGn4VFHuc0+wTRckcXiijoAXxpmFdaIsFBl5Aai4d6C/r0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Spam404
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
