env:
  global:
    - secure: BMtAcFkbrh3MlJX5uQJL8F1scfmbvor73c9FshJVZ2PCn3NaIt8+cwQLEyFyYH4PgP55KE20EbAPEpxTsweJijLXdBWlTbfjPp718CBWSeM/S0bOeVaHcHUJ8KBimACh6zreGwK6l7W7p6o6OpacoVIlW0+K0/jV+cIhDmX2himNEI26B+sKmc/4vhsCRYx8DBNAyPcTfVbSwWN/DXT0Nq9WLOfl7fkahf3X1saQ+qyn64zFOlemRfA+c2q5y3ItM7UW3aMYaVb/UmlQynZ9Cx/ZuW92EDZyA2+mbYj1VttSVmp+kLP/WwYxw9Z9i0sgP8lDfTX1RTXhv3vnkz1YRdmaGu+kPMNAptabUH0C86XUvZliM40w9Qkua0Yv32oHpOAnPDB/icCfckXRIjb4x60jP70uzhT2A/P6gbJ1iD/lSDNb6OXwAbW5GN7+fYahlPdCWchSXLEM/ZrtuJCwCWqYO4L+AWwBpl/LjJAfcTaYmwb0RDrSADaJ6nVQBGHgqFk8wsqevv/2Gi7UnbBQwoWdfMArGbzKu0RAD1CNTFqmvuMwPEoycjIMpVD2/Zmqs3vJgLJ6Uh0WMCxddZmWi0acZyTrQB5DUo5W3cecHWNq012AoIt7kbfa+wE0sJX8MNM0Y5VTEEcXCbbdet6s9dyzteXngs+LSBKH/myBNig=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Spam404
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
