addons:
    apt:
        packages:
        - dos2unix
dist: bionic
env:
    global:
    -   secure: dCEuR7jeJGZwTveR3Uun+eIs/Ryd3pHn/CKe0KzdugjD7JNtoeMGbHH2lP3x49gVrJF705Q6xaK+amjuFysKPxgNI5DketUtIcbb2tL5mmLMbRzKTbbokLFdJd5w/Ac1M9t14M6PJoO5SI7NuKLui1R4SGQT7fwnrplG8A5KwKUL3DBV0rh7pRKV+cA8ymE0CpjN1d/EB0OH9UA95BgfAhNJhKGwg6ksNWWcq9lzjli9pRQvZA2gS7kOGkFMCYW7JWGlwrDdwtdDSg6oHupuGiV1Ys3u6dFso9GHqTd8l1+xOPXrwGASmFAPfnR2IdhZ5BZF0r5lqyQviJQOsCrvLpC4MOODMQ1+m2kjhDZQmOcHM44wa6e3tnmjmnRx8Ty0xNvKx/czBh84XqccgLs8o8eaxoLUGlJT0923aiyjcV0nd2WoK7yDPGnVCiAE4V/x/0dZ+eWDwnfYsFsv2As6jTKqCb/Z/vyg15eLHwjjVq/EM4UbKcXD/dv2R+32JDMnXnKgNH6jQf89QRK6r5fgm7ZtDMZGbbvgx7AZ8wKl9Wclt4t2iLMPlSgVC+A6qKf4ME8SUwTH05W18REikW+UCqgGxA2KtzetUiKKm+1gF/Z7YQxlGQC+WTOEQA1yQaJ7W9V+NKVixjTqx5Ln0R6UnhkhHMqlRfahHdNCt7CKTAA=
    -   GIT_NAME: Travis CI
    -   GIT_EMAIL: dead-hosts@funilrys.com
    -   TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Spam404
    -   GIT_BRANCH: master
    -   UPDATE_LOCATION: https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/repository-structure/master/update.py
    -   ADMINISTATION_LOCATION: https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/repository-structure/master/administration.py
install:
- export PATH="${HOME}/miniconda/bin:${PATH}"
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p ${HOME}/miniconda
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda create -q -n test-environment python="${PYTHON_VERSION}"
- source activate test-environment
- python -VV
- pip --version
- pip install ultimate-hosts-blacklist-input-repo-updater
- rm miniconda.sh
language: generic
matrix:
    fast_finish: true
notifications:
    email:
        on_failure: always
        on_success: never
        recipients:
        - dead-hosts@funilrys.com
        - mitchellkrogza+ultimatehostsblacklist@gmail.com
script:
- ultimate-hosts-blacklist-input-repo-updater --version
- ultimate-hosts-blacklist-input-repo-updater -m
