env:
  global:
    - secure: ND0Ee5UC37+3A/71DfSuYC8MYd5jJGBQAC9hwAgObPiLHtw5TK07AMD+UlZwbRymlT+77TK2Ut+gqQhOd0387oaCWuKG51fALkxk5nHlxstlwqCy50ZcV3HscUTqMW4lAwfNkRZ+/gc7yDUgV5bg+lUlk7PO4hXVPlW2kx24Yb43b5Ob7k/IusYtXuuKkyc7GgXGijwzsiXq6Qkhx9ASXfAfHREFYZJBQ3Adc5plbDAJKdCaTMabE9AMmTQI3qjfThCaS5ik/mhTIfm87mTQbihbT/nY6d3xBSUb4j2dG9J78Tmn9o8I2jB8LSpThroQJAq5GqjYeRWNtuMn5zd9Z0pglAcUdOH7AyjN4p/O8aB5jfdZZ8WceL57vKhAGV36wdpK7AnBaY2oxOkPeMgyrzYZ2mHwY2UkwcsD76kSD0DJd9rQfkfuIP2AeHXJ4sVdNp2hu2ttkpUqmtnbReCIbegxcNcgdlOEsAWG3uDXzaCtwQTANv6tB+4AfoIUq2iHZzsctBMchadfyhOWabF3PLHnfF2Qm+cUKBxsR85iHQIvF8X/of4LKoKPXen+Qu+A6V8R47IoMNN3wAh0DZWx255GIxw/x18Nhir+MN83n9z5Wo8YgtEM6SRRv1BGVLp6PJs9Fc2oCHSum0bUx02+7hegxWzqnF73QVn7V+6NFQ0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Spam404
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
